### ISSUE TITLE
Problem compiling in .NET Core 3.1 project

### ISSUE THREAD

**Issue by linuschinsay** [alfusinigoj/moq_datareader#5]
I've a .NET Core 3.1 project and it has compiling problem when I build my project after referencing this package.

![image](https://user-images.githubusercontent.com/55272463/160801958-bda23142-8835-408d-884c-b3214589885c.png)

**Comment by alfusinigoj** [comment]
@linuschinsay currently it is published to support net5.0 and above. I shall add support for lower versions and let you know.

**Comment by alfusinigoj** [comment]
@linuschinsay Can you please check with the latest version 1.0.2? Hope it helps.

**Comment by alfusinigoj** [comment]
I am closing this, as the new version work well with `netcoreapp3.1`
